//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.AhkTest8.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.AhkTest8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateEngine.
        /// </summary>
        internal static string CreateAutoHotkeyEngine_Description {
            get {
                return ResourceManager.GetString("CreateAutoHotkeyEngine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateEngine.
        /// </summary>
        internal static string CreateAutoHotkeyEngine_FriendlyName {
            get {
                return ResourceManager.GetString("CreateAutoHotkeyEngine_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of ActionError.
        /// </summary>
        internal static string Error_ActionError_Description {
            get {
                return ResourceManager.GetString("Error_ActionError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name of ActionError.
        /// </summary>
        internal static string Error_ActionError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ActionError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass up to 10 args to function.
        /// </summary>
        internal static string ExecFunction_Arg01_Description {
            get {
                return ResourceManager.GetString("ExecFunction_Arg01_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call CreateAutoHotkeyEngine and LoadFunctionFile first..
        /// </summary>
        internal static string ExecFunction_Description {
            get {
                return ResourceManager.GetString("ExecFunction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecFunction.
        /// </summary>
        internal static string ExecFunction_FriendlyName {
            get {
                return ResourceManager.GetString("ExecFunction_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String with AHK function to call.
        /// </summary>
        internal static string ExecFunction_FunctionName_Description {
            get {
                return ResourceManager.GetString("ExecFunction_FunctionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create engine, load script using IsReady().
        /// </summary>
        internal static string ExecRaw_Description {
            get {
                return ResourceManager.GetString("ExecRaw_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecRaw.
        /// </summary>
        internal static string ExecRaw_FriendlyName {
            get {
                return ResourceManager.GetString("ExecRaw_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute script - needs engine - no wait or terminate.
        /// </summary>
        internal static string ExecRawInstant_Description {
            get {
                return ResourceManager.GetString("ExecRawInstant_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecRawInstant.
        /// </summary>
        internal static string ExecRawInstant_FriendlyName {
            get {
                return ResourceManager.GetString("ExecRawInstant_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get variable from loaded AutoHotkey engine.
        /// </summary>
        internal static string GetVar_Description {
            get {
                return ResourceManager.GetString("GetVar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVar.
        /// </summary>
        internal static string GetVar_FriendlyName {
            get {
                return ResourceManager.GetString("GetVar_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load existing engine, file, call function.
        /// </summary>
        internal static string LoadEngineAndFile_Description {
            get {
                return ResourceManager.GetString("LoadEngineAndFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadEngineAndFile.
        /// </summary>
        internal static string LoadEngineAndFile_FriendlyName {
            get {
                return ResourceManager.GetString("LoadEngineAndFile_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptName.
        /// </summary>
        internal static string LoadEngineAndFile_ScriptName_FriendlyName {
            get {
                return ResourceManager.GetString("LoadEngineAndFile_ScriptName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates engine, loads script, calls function.
        /// </summary>
        internal static string LoadFile_Description {
            get {
                return ResourceManager.GetString("LoadFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadFile.
        /// </summary>
        internal static string LoadFile_FriendlyName {
            get {
                return ResourceManager.GetString("LoadFile_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String with AHK function to call.
        /// </summary>
        internal static string LoadFile_FunctionName_Description {
            get {
                return ResourceManager.GetString("LoadFile_FunctionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionName.
        /// </summary>
        internal static string LoadFile_FunctionName_FriendlyName {
            get {
                return ResourceManager.GetString("LoadFile_FunctionName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String path of AHK Script.
        /// </summary>
        internal static string LoadFile_ScriptName_Description {
            get {
                return ResourceManager.GetString("LoadFile_ScriptName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptName.
        /// </summary>
        internal static string LoadFile_ScriptName_FriendlyName {
            get {
                return ResourceManager.GetString("LoadFile_ScriptName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads a script with function(s) to call.
        /// </summary>
        internal static string LoadFunctionFile_Description {
            get {
                return ResourceManager.GetString("LoadFunctionFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadFunctionFile.
        /// </summary>
        internal static string LoadFunctionFile_FriendlyName {
            get {
                return ResourceManager.GetString("LoadFunctionFile_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a variable in loaded AutoHotkey engine.
        /// </summary>
        internal static string SetVar_Description {
            get {
                return ResourceManager.GetString("SetVar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVar.
        /// </summary>
        internal static string SetVar_FriendlyName {
            get {
                return ResourceManager.GetString("SetVar_FriendlyName", resourceCulture);
            }
        }
    }
}
