//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhkTest2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AhkTest2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of ActionError.
        /// </summary>
        internal static string Error_ActionError_Description {
            get {
                return ResourceManager.GetString("Error_ActionError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name of ActionError.
        /// </summary>
        internal static string Error_ActionError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ActionError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadScriptAndCallFunction.
        /// </summary>
        internal static string LoadScriptAndCallFunction_Description {
            get {
                return ResourceManager.GetString("LoadScriptAndCallFunction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadScriptAndCallFunction.
        /// </summary>
        internal static string LoadScriptAndCallFunction_FriendlyName {
            get {
                return ResourceManager.GetString("LoadScriptAndCallFunction_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionName.
        /// </summary>
        internal static string LoadScriptAndCallFunction_FunctionName_Description {
            get {
                return ResourceManager.GetString("LoadScriptAndCallFunction_FunctionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionName.
        /// </summary>
        internal static string LoadScriptAndCallFunction_FunctionName_FriendlyName {
            get {
                return ResourceManager.GetString("LoadScriptAndCallFunction_FunctionName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptName.
        /// </summary>
        internal static string LoadScriptAndCallFunction_ScriptName_Description {
            get {
                return ResourceManager.GetString("LoadScriptAndCallFunction_ScriptName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptName.
        /// </summary>
        internal static string LoadScriptAndCallFunction_ScriptName_FriendlyName {
            get {
                return ResourceManager.GetString("LoadScriptAndCallFunction_ScriptName_FriendlyName", resourceCulture);
            }
        }
    }
}
